apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole
spec:
  interval: 24h
  timeout: 10m
  chart:
    spec:
      chart: podinfo
      version: '2.26.*'
      sourceRef:
        kind: HelmRepository
        name: pihole
      interval: 5m
  releaseName: pihole
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: pihole-values
