apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sources
  namespace: flux-system
spec:
  interval: 1d
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./sources
  prune: true
